<?php
/**
 * touristspot CPT 用 ACF フィールドグループ登録。
 *
 * 観光地情報の編集フィールドを3タブ構成で定義し、WPGraphQLにも公開します。
 */

if (!defined('ABSPATH')) {
    exit;
}

add_action('acf/init', function (): void {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group([
        'key' => 'group_touristspot',
        'title' => '観光地情報',
        'fields' => [
            [
                'key' => 'field_ts_tab_basic',
                'label' => '基本情報',
                'type' => 'tab',
                'instructions' => 'カテゴリ、キャッチコピー、サムネイルを設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_category',
                'label' => 'カテゴリ',
                'name' => 'category',
                'type' => 'select',
                'instructions' => '観光地のカテゴリを選択してください。',
                'required' => 1,
                'choices' => [
                    'nature' => '自然・景観',
                    'onsen' => '温泉',
                    'gourmet' => 'グルメ',
                    'lodging' => '宿泊',
                    'experience' => '体験・アクティビティ',
                    'culture' => '文化・歴史',
                    'view' => '公園・展望',
                ],
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'return_format' => 'value',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_catch_copy',
                'label' => 'キャッチコピー',
                'name' => 'catch_copy',
                'type' => 'text',
                'instructions' => '一覧や詳細冒頭に表示する短い紹介文を入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_thumbnail_image',
                'label' => 'サムネイル画像',
                'name' => 'thumbnail_image',
                'type' => 'image',
                'instructions' => '動画URLが未入力の場合に表示する画像を選択してください。',
                'required' => 1,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_thumbnail_video_url',
                'label' => 'サムネイル動画URL',
                'name' => 'thumbnail_video_url',
                'type' => 'url',
                'instructions' => 'YouTubeやVimeoなど、サムネイルとして優先表示する動画URLを入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_tab_detail',
                'label' => '詳細・解説',
                'type' => 'tab',
                'instructions' => 'スポットの魅力、写真、訪問に向く季節を設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_description',
                'label' => '説明文',
                'name' => 'description',
                'type' => 'wysiwyg',
                'instructions' => 'スポットの魅力や特徴を入力してください。',
                'required' => 1,
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_gallery_images',
                'label' => 'ギャラリー画像',
                'name' => 'gallery_images',
                'type' => 'gallery',
                'instructions' => '詳細ページで表示する複数の写真を選択してください。',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'insert' => 'append',
                'library' => 'all',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_best_season',
                'label' => 'おすすめ季節',
                'name' => 'best_season',
                'type' => 'text',
                'instructions' => '訪問におすすめの季節を入力してください。例: 夏(7-8月)',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_tab_visit',
                'label' => '訪問情報',
                'type' => 'tab',
                'instructions' => '住所、アクセス、営業時間、料金、連絡先を設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_address',
                'label' => '住所',
                'name' => 'address',
                'type' => 'text',
                'instructions' => '観光地の住所を入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_access_info',
                'label' => 'アクセス情報',
                'name' => 'access_info',
                'type' => 'textarea',
                'instructions' => '港や空港からのアクセス方法を入力してください。例: 鴛泊港から車で15分',
                'required' => 0,
                'rows' => 4,
                'new_lines' => 'br',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_open_hours',
                'label' => '営業時間・開放時間',
                'name' => 'open_hours',
                'type' => 'text',
                'instructions' => '営業時間や開放時間を入力してください。例: 常時開放',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_closed_days',
                'label' => '定休日',
                'name' => 'closed_days',
                'type' => 'text',
                'instructions' => '定休日や休業期間がある場合は入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_price',
                'label' => '料金',
                'name' => 'price',
                'type' => 'text',
                'instructions' => '入場料や利用料金を入力してください。例: 無料、大人500円',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_phone',
                'label' => '電話番号',
                'name' => 'phone',
                'type' => 'text',
                'instructions' => '問い合わせ先の電話番号を入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ts_website_url',
                'label' => '公式サイトURL',
                'name' => 'website_url',
                'type' => 'url',
                'instructions' => '公式サイトや関連ページのURLを入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'touristspot',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'active' => true,
        'show_in_rest' => 1,
        'show_in_graphql' => 1,
        'graphql_field_name' => 'touristspotFields',
    ]);
});
