<?php
/**
 * job_posting CPT 用 ACF フィールドグループ登録。
 *
 * 求人情報の編集フィールドを5タブ構成で定義し、WPGraphQLにも公開します。
 */

if (!defined('ABSPATH')) {
    exit;
}

add_action('acf/init', function (): void {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group([
        'key' => 'group_job_posting',
        'title' => '求人情報',
        'fields' => [
            [
                'key' => 'field_jp_tab_basic',
                'label' => '募集の基本',
                'type' => 'tab',
                'instructions' => '雇用形態、キャッチコピー、サムネイルを設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_employment_type',
                'label' => '雇用形態',
                'name' => 'employment_type',
                'type' => 'select',
                'instructions' => '求人の雇用形態を選択してください。',
                'required' => 1,
                'choices' => [
                    'regular' => '正規職員',
                    'fiscal_year_full' => '会計年度任用（フル）',
                    'fiscal_year_part' => '会計年度任用（パート）',
                    'entrusted' => '嘱託職員',
                    'fixed_term' => '任期付職員',
                    'temporary' => '臨時職員',
                ],
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'return_format' => 'value',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_catch_copy',
                'label' => 'キャッチコピー',
                'name' => 'catch_copy',
                'type' => 'text',
                'instructions' => '一覧や詳細冒頭に表示する短い紹介文を入力してください。',
                'required' => 0,
                'maxlength' => '',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_thumbnail_image',
                'label' => 'サムネイル画像',
                'name' => 'thumbnail_image',
                'type' => 'image',
                'instructions' => '動画URLが未入力の場合に表示する画像を選択してください。',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_thumbnail_video_url',
                'label' => 'サムネイル動画URL',
                'name' => 'thumbnail_video_url',
                'type' => 'url',
                'instructions' => 'YouTubeやVimeoなど、サムネイルとして優先表示する動画URLを入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_tab_description',
                'label' => '業務内容',
                'type' => 'tab',
                'instructions' => '業務内容と応募者向けの補足情報を設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_description',
                'label' => '業務内容',
                'name' => 'description',
                'type' => 'wysiwyg',
                'instructions' => '担当する仕事の内容を具体的に入力してください。',
                'required' => 1,
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_desired_person',
                'label' => '求める人材',
                'name' => 'desired_person',
                'type' => 'textarea',
                'instructions' => '向いている人物像や歓迎する姿勢を入力してください。',
                'required' => 0,
                'rows' => 4,
                'new_lines' => 'br',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_required_qualifications',
                'label' => '必要資格',
                'name' => 'required_qualifications',
                'type' => 'textarea',
                'instructions' => '応募に必要な資格や免許を入力してください。',
                'required' => 0,
                'rows' => 4,
                'new_lines' => 'br',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_tab_conditions',
                'label' => '条件・待遇',
                'type' => 'tab',
                'instructions' => '給与、勤務時間、休日、福利厚生などを設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_salary',
                'label' => '給与',
                'name' => 'salary',
                'type' => 'text',
                'instructions' => '一覧表示向けの給与概要を入力してください。例: 月額18.5万円〜',
                'required' => 1,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_salary_detail',
                'label' => '給与詳細',
                'name' => 'salary_detail',
                'type' => 'textarea',
                'instructions' => '手当や昇給など、給与に関する補足を入力してください。',
                'required' => 0,
                'rows' => 4,
                'new_lines' => 'br',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_work_hours',
                'label' => '勤務時間',
                'name' => 'work_hours',
                'type' => 'text',
                'instructions' => '一覧表示向けの勤務時間を入力してください。例: 8:30〜17:15',
                'required' => 1,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_work_hours_detail',
                'label' => '勤務時間詳細',
                'name' => 'work_hours_detail',
                'type' => 'textarea',
                'instructions' => 'シフト、休憩、時間外勤務などの補足を入力してください。',
                'required' => 0,
                'rows' => 4,
                'new_lines' => 'br',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_holiday',
                'label' => '休日・休暇',
                'name' => 'holiday',
                'type' => 'textarea',
                'instructions' => '休日、休暇制度、有給休暇などを入力してください。',
                'required' => 0,
                'rows' => 4,
                'new_lines' => 'br',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_social_insurance',
                'label' => '社会保険',
                'name' => 'social_insurance',
                'type' => 'text',
                'instructions' => '社会保険の加入状況を入力してください。例: 各種完備',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_benefits',
                'label' => '福利厚生',
                'name' => 'benefits',
                'type' => 'textarea',
                'instructions' => '住居サポート以外の福利厚生を入力してください。',
                'required' => 0,
                'rows' => 4,
                'new_lines' => 'br',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_housing_support_available',
                'label' => '住居サポートあり',
                'name' => 'housing_support_available',
                'type' => 'true_false',
                'instructions' => '住居サポートがある場合はオンにしてください。',
                'required' => 0,
                'ui' => 1,
                'default_value' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_housing_support_detail',
                'label' => '住居サポート詳細',
                'name' => 'housing_support_detail',
                'type' => 'textarea',
                'instructions' => '住居サポートの内容、対象条件、補助額などを入力してください。',
                'required' => 0,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_jp_housing_support_available',
                            'operator' => '==',
                            'value' => '1',
                        ],
                    ],
                ],
                'rows' => 4,
                'new_lines' => 'br',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_smoking_policy',
                'label' => '受動喫煙対策',
                'name' => 'smoking_policy',
                'type' => 'text',
                'instructions' => '受動喫煙対策を必ず入力してください。例: 敷地内禁煙',
                'required' => 1,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_trial_period',
                'label' => '試用・研修期間',
                'name' => 'trial_period',
                'type' => 'text',
                'instructions' => '試用期間や研修期間がある場合は入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_tab_location',
                'label' => '勤務地・表示位置',
                'type' => 'tab',
                'instructions' => '勤務地情報と3Dマップ上のピン位置を設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_work_address',
                'label' => '勤務地住所',
                'name' => 'work_address',
                'type' => 'text',
                'instructions' => '勤務地の住所を入力してください。',
                'required' => 1,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_work_address_detail',
                'label' => '勤務地詳細',
                'name' => 'work_address_detail',
                'type' => 'textarea',
                'instructions' => '建物名、部署、フロアなど住所の補足を入力してください。',
                'required' => 0,
                'rows' => 3,
                'new_lines' => 'br',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_pin_location',
                'label' => '表示するピン位置',
                'name' => 'pin_location',
                'type' => 'select',
                'instructions' => '3Dマップ上で求人をまとめて表示する位置を選択してください。',
                'required' => 1,
                'choices' => [
                    'town_hall' => '役場本庁舎',
                    'health_center' => '保健センター',
                    'airport' => '利尻空港',
                    'oniwaki' => '鬼脇地区',
                ],
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'return_format' => 'value',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_tab_apply',
                'label' => '応募',
                'type' => 'tab',
                'instructions' => '応募後の流れを設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_jp_application_flow',
                'label' => '応募後の流れ',
                'name' => 'application_flow',
                'type' => 'wysiwyg',
                'instructions' => '応募後の手続き、必要書類、選考の流れを入力してください。',
                'required' => 1,
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'show_in_graphql' => 1,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'job_posting',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'active' => true,
        'show_in_rest' => 1,
        'show_in_graphql' => 1,
        'graphql_field_name' => 'jobPostingFields',
    ]);
});
