<?php
/**
 * event CPT 用 ACF フィールドグループ登録。
 *
 * イベント情報の編集フィールドを4タブ構成で定義し、WPGraphQLにも公開します。
 */

if (!defined('ABSPATH')) {
    exit;
}

add_action('acf/init', function (): void {
    if (!function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group([
        'key' => 'group_event',
        'title' => 'イベント情報',
        'fields' => [
            [
                'key' => 'field_ev_tab_basic',
                'label' => '基本情報',
                'type' => 'tab',
                'instructions' => 'カテゴリ、キャッチコピー、サムネイルを設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_category',
                'label' => 'カテゴリ',
                'name' => 'category',
                'type' => 'select',
                'instructions' => 'イベントのカテゴリを選択してください。',
                'required' => 1,
                'choices' => [
                    'festival' => 'まつり・伝統行事',
                    'workshop' => '体験・ワークショップ',
                    'seminar' => 'セミナー・講演会',
                    'recruitment' => '募集・ボランティア',
                    'sports' => 'スポーツ',
                    'culture' => '文化・芸術',
                ],
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 1,
                'return_format' => 'value',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_catch_copy',
                'label' => 'キャッチコピー',
                'name' => 'catch_copy',
                'type' => 'text',
                'instructions' => '一覧や詳細冒頭に表示する短い紹介文を入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_thumbnail_image',
                'label' => 'サムネイル画像',
                'name' => 'thumbnail_image',
                'type' => 'image',
                'instructions' => '動画URLが未入力の場合に表示する画像を選択してください。',
                'required' => 1,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'library' => 'all',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_thumbnail_video_url',
                'label' => 'サムネイル動画URL',
                'name' => 'thumbnail_video_url',
                'type' => 'url',
                'instructions' => 'YouTubeやVimeoなど、サムネイルとして優先表示する動画URLを入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_tab_schedule',
                'label' => 'スケジュール・開催情報',
                'type' => 'tab',
                'instructions' => '開催日時、毎年開催の有無、主催者を設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_date_display_type',
                'label' => '日程の表示方法',
                'name' => 'date_display_type',
                'type' => 'select',
                'required' => 1,
                'choices' => [
                    'exact' => '日付を指定する',
                    'period' => '期間で表現する(上旬・中旬・下旬)',
                ],
                'default_value' => 'exact',
                'return_format' => 'value',
                'multiple' => 0,
                'ui' => 0,
                'show_in_graphql' => 1,
                'instructions' => '開催日が確定していない場合は「期間で表現する」を選択してください。',
            ],
            [
                'key' => 'field_ev_period_month',
                'label' => '開催月',
                'name' => 'period_month',
                'type' => 'select',
                'required' => 0,
                'choices' => [
                    '1' => '1月',
                    '2' => '2月',
                    '3' => '3月',
                    '4' => '4月',
                    '5' => '5月',
                    '6' => '6月',
                    '7' => '7月',
                    '8' => '8月',
                    '9' => '9月',
                    '10' => '10月',
                    '11' => '11月',
                    '12' => '12月',
                ],
                'return_format' => 'value',
                'multiple' => 0,
                'show_in_graphql' => 1,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_ev_date_display_type',
                            'operator' => '==',
                            'value' => 'period',
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_ev_period_range',
                'label' => '時期',
                'name' => 'period_range',
                'type' => 'select',
                'required' => 0,
                'choices' => [
                    'early' => '上旬',
                    'mid' => '中旬',
                    'late' => '下旬',
                ],
                'return_format' => 'value',
                'multiple' => 0,
                'show_in_graphql' => 1,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_ev_date_display_type',
                            'operator' => '==',
                            'value' => 'period',
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_ev_start_datetime',
                'label' => '開始日時',
                'name' => 'start_datetime',
                'type' => 'date_picker',
                'instructions' => 'イベントの開始日時を入力してください。',
                'required' => 1,
                'display_format' => 'Y/m/d',
                'return_format' => 'Y-m-d',
                'first_day' => 1,
                'show_in_graphql' => 1,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_ev_date_display_type',
                            'operator' => '==',
                            'value' => 'exact',
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_ev_end_datetime',
                'label' => '終了日時',
                'name' => 'end_datetime',
                'type' => 'date_picker',
                'instructions' => '単日イベントでも終了日時は必須入力です。',
                'required' => 1,
                'display_format' => 'Y/m/d',
                'return_format' => 'Y-m-d',
                'first_day' => 1,
                'show_in_graphql' => 1,
                'conditional_logic' => [
                    [
                        [
                            'field' => 'field_ev_date_display_type',
                            'operator' => '==',
                            'value' => 'exact',
                        ],
                    ],
                ],
            ],
            [
                'key' => 'field_ev_is_recurring',
                'label' => '毎年開催',
                'name' => 'is_recurring',
                'type' => 'true_false',
                'instructions' => '毎年開催されるイベントの場合はオンにしてください。',
                'required' => 0,
                'ui' => 1,
                'default_value' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_recurrence_note',
                'label' => '開催パターン',
                'name' => 'recurrence_note',
                'type' => 'text',
                'instructions' => '毎年開催の場合の開催パターンを入力してください。例: 毎年7月最終週',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_tab_detail',
                'label' => '詳細・解説',
                'type' => 'tab',
                'instructions' => 'イベントの説明文と写真を設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_description',
                'label' => '説明文',
                'name' => 'description',
                'type' => 'wysiwyg',
                'instructions' => 'イベントの内容や魅力を入力してください。',
                'required' => 1,
                'tabs' => 'all',
                'toolbar' => 'full',
                'media_upload' => 1,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_gallery_images',
                'label' => 'ギャラリー画像',
                'name' => 'gallery_images',
                'type' => 'gallery',
                'instructions' => 'イベント写真を選択してください。過去開催の様子の写真も使用できます。',
                'required' => 0,
                'return_format' => 'array',
                'preview_size' => 'medium',
                'insert' => 'append',
                'library' => 'all',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_tab_venue',
                'label' => '会場・申込',
                'type' => 'tab',
                'instructions' => '会場、ピン位置、参加費、申込先、問い合わせ先を設定します。',
                'placement' => 'top',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_venue_name',
                'label' => '会場名',
                'name' => 'venue_name',
                'type' => 'text',
                'instructions' => '会場名を入力してください。例: 鬼脇地区会館',
                'required' => 1,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_address',
                'label' => '住所',
                'name' => 'address',
                'type' => 'text',
                'instructions' => '会場の住所を入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_access_info',
                'label' => 'アクセス情報',
                'name' => 'access_info',
                'type' => 'textarea',
                'instructions' => '会場までのアクセス方法を入力してください。',
                'required' => 0,
                'rows' => 4,
                'new_lines' => 'br',
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_pin_reference',
                'label' => 'ピン位置の参照',
                'name' => 'pin_reference',
                'type' => 'text',
                'instructions' => 'PIN_POSITIONSのキーを入力してください。例: himenuma / oniwaki / rishirisan_opening',
                'required' => 1,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_price',
                'label' => '参加費',
                'name' => 'price',
                'type' => 'text',
                'instructions' => '参加費を入力してください。例: 無料、500円',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_registration_url',
                'label' => '申込先URL',
                'name' => 'registration_url',
                'type' => 'url',
                'instructions' => '外部申込フォームや案内ページのURLを入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
            [
                'key' => 'field_ev_contact',
                'label' => '問い合わせ先',
                'name' => 'contact',
                'type' => 'text',
                'instructions' => '問い合わせ先の名称、電話番号、メールアドレスなどを入力してください。',
                'required' => 0,
                'show_in_graphql' => 1,
            ],
        ],
        'location' => [
            [
                [
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'event',
                ],
            ],
        ],
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'active' => true,
        'show_in_rest' => 1,
        'show_in_graphql' => 1,
        'graphql_field_name' => 'eventFields',
    ]);
});
