<?php
/**
 * 旧リシリクルート（sumple-site02.click / rishirifuji テーマ）の求人 19 件を
 * 現行 job_posting CPT に一括投入する。
 *
 * 実行方法（Local by Flywheel の「Open Site Shell」内で）:
 *   wp eval-file wp-content/themes/rishirecruit2026/scripts/import-rishirecruit-jobs.php
 *
 * 実行後、Tools > Export で「求人」を書き出し、Lolipop 側で Tools > Import する。
 *
 * ★このスクリプトは冒頭で既存の job_posting を全削除（force delete）する★
 * 「投稿を全削除→新規 19 件を投入」する用途に特化。
 *
 * 業務内容(description)・給与・勤務時間などは旧サイトの原文をそのまま格納。
 * catch_copy / smoking_policy / application_flow など旧サイトで未入力だった項目は
 * 現行 ACF の required に合わせて既定値を補完する（AGENTS.md「Report Honestly」）。
 */

if (!defined('ABSPATH')) {
    exit;
}

/* ---------- Step 1: 既存 job_posting をすべて削除 ---------- */

$existing_ids = get_posts([
    'post_type'      => 'job_posting',
    'post_status'    => 'any',
    'posts_per_page' => -1,
    'fields'         => 'ids',
    'suppress_filters' => true,
]);

$deleted = 0;
foreach ($existing_ids as $existing_id) {
    if (wp_delete_post($existing_id, true)) {
        $deleted++;
    }
}

/* ---------- Step 2: 19 件の求人データ ---------- */

$default_flow = "本ページ下部の応募フォームからお申し込みください。担当より追ってご連絡いたします。\n電話でのお問い合わせ: 0163-82-1111";
$default_smoking = '敷地内禁煙';

$jobs = [
    [
        'slug' => 'job-119',
        'title' => '地域・学校コーディネーター',
        'area' => 'oshidomari',
        'catch_copy' => null,
        'job_category' => null,
        'recruitment_count' => null,
        'employment_type' => 'part_time',
        'description' => "・地域と学校のつなぎ役（コーディネーター）\n・部活動の地域移行支援（団体との委託業務や施設利用（学校開放等）の調整）\n・放課後子ども教室の運営",
        'required_qualifications' => "学歴不問/未経験OK\n\n【必須】\n・普通自動車免許",
        'salary' => '月給:170,000～200,000円程度 もしくは時給:1,200円',
        'salary_detail' => null,
        'work_hours' => '08:30～17:00',
        'work_hours_detail' => "実働:7時間30分\n休憩:60分\n\n＊勤務形態により変則可能",
        'holiday' => '週休2日制 有給休暇あり',
        'social_insurance' => '厚生年金保険 / 雇用保険',
        'benefits' => null,
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => null,
        'trial_period' => null,
        'work_address' => '北海道利尻富士町鴛泊字富士野6',
        'work_address_detail' => "〒097-0101 利尻富士町鴛泊字富士野６\n利尻富士町役場（教育委員会）\n鴛泊フェリーターミナルより車で5分",
        'pin_location' => 'town_hall',
        'application_flow' => null,
    ],
    [
        'slug' => 'job-120',
        'title' => '土木技術職員',
        'area' => 'oshidomari',
        'catch_copy' => null,
        'job_category' => '土木設計・積算・工事監理',
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => "道路及び河川事業等の\n土木設計・積算・工事監理及び土木災害への\n復旧工事対応、道路の維持補修。\nその他一般行政事務等。",
        'required_qualifications' => "大学、高専、専門学校、高等学校において土木専門課程を履修した方又は卒業見込みの方\n普通自動車免許を所持又は取得見込の方\n日本国籍を有する方\n地方公務員法第16条各号の欠格条項に該当しない方",
        'salary' => '月給 201,000円～220,000円',
        'salary_detail' => "短大卒 201,000円\n大学卒 220,000円\n※初任給は、経験に応じ加算される場合があります。\n期末手当、勤勉手当、寒冷地手当、住居手当、通勤手当、扶養手当",
        'work_hours' => '固定時間制',
        'work_hours_detail' => '午前8時30分～午後5時15分',
        'holiday' => "完全週休2日制（土日祝休み）\n年末年始（12/31～1/5）\n年次有給休暇（年20日付与、初年度最大15日付与）\n夏季休暇、結婚、忌引、出産等の休暇制度があります。",
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "市町村職員共済組合加入（健康保険、厚生年金）\n退職手当組合加入",
        'housing_support_available' => 1,
        'housing_support_detail' => '住居手当',
        'smoking_policy' => null,
        'trial_period' => '6ヶ月',
        'work_address' => '北海道利尻富士町鴛泊字富士野6',
        'work_address_detail' => "利尻富士町役場　建設課\n〒097-0101\n利尻郡利尻富士町鴛泊字富士野6番地",
        'pin_location' => 'town_hall',
        'application_flow' => '応募フォーム入力（氏名、連絡先、住所等必須項目）',
    ],
    [
        'slug' => 'job-123',
        'title' => '看護師',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => '看護職',
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => "・看護業務\n（夜間待機当番、バルーン交換、食事介助、胃瘻、人工肛門ケア、排泄介助、フットケア、バイタル、たん吸引、通院付添、褥瘡処置、指示の定期注射、採血、配薬、夜勤（介護業務））\n・簡単なＰＣ入力あり\n・一部、介護業務フォロー（オムツ交換、移乗動作など）",
        'required_qualifications' => '看護師免許（正看護師、准看護師）',
        'salary' => '月給 188,000円～',
        'salary_detail' => '期末勤勉手当（年4.6月）、寒冷地手当（11～3月）、住居手当、通勤手当、扶養手当、時間外勤務手当など',
        'work_hours' => 'シフト制',
        'work_hours_detail' => "勤務：07時30分～16時15分\nＣ勤：08時30分～17時15分\n夜勤：16時30分～09時00分",
        'holiday' => '有給休暇、夏季休暇、結婚、忌引、出産等の特別休暇あり',
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "市町村職員共済組合加入\n退職手当組合加入",
        'housing_support_available' => 1,
        'housing_support_detail' => '住居手当あり',
        'smoking_policy' => null,
        'trial_period' => '6ケ月',
        'work_address' => '北海道利尻郡利尻富士町鬼脇字鬼脇205-1',
        'work_address_detail' => "〒097-0211\n北海道利尻郡利尻富士町鬼脇字鬼脇205番地1\n鴛泊フェリーターミナルより車で30分\n利尻空港より車で35分",
        'pin_location' => 'oniwaki',
        'application_flow' => '応募フォームより申請',
    ],
    [
        'slug' => 'job-124',
        'title' => '介護員',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => '介護業務',
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => "・介護業務\n（入浴介助、食事介助などの一般介護業務のほか夜勤）\n・簡単なＰＣ入力あり",
        'required_qualifications' => '介護福祉士、実務者研修、初任者研修',
        'salary' => '月給 188,000円～',
        'salary_detail' => '期末勤勉手当（年4.6月）、寒冷地手当（11～3月）、住居手当、通勤手当、扶養手当、時間外勤務手当など',
        'work_hours' => 'シフト制',
        'work_hours_detail' => "日勤：07時45分～16時30分\nＣ勤：08時45分～17時30分\n夜勤：16時30分～09時00分",
        'holiday' => '有給休暇、夏季休暇、結婚、忌引、出産等の特別休暇あり',
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => '市町村職員共済組合加入、退職手当組合加入',
        'housing_support_available' => 1,
        'housing_support_detail' => '住居手当',
        'smoking_policy' => null,
        'trial_period' => '6ケ月',
        'work_address' => '北海道利尻郡利尻富士町鬼脇字鬼脇205-1',
        'work_address_detail' => "〒097-0211\n北海道利尻郡利尻富士町鬼脇字鬼脇205番地1\n鴛泊フェリーターミナルより車で30分\n利尻空港より車で35分",
        'pin_location' => 'oniwaki',
        'application_flow' => '応募フォームで必要情報入力（姓名・性別・生年月日・電話・メール・住所）',
    ],
    [
        'slug' => 'job-125',
        'title' => '臨時介護員',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => '介護業務',
        'recruitment_count' => null,
        'employment_type' => 'temporary',
        'description' => "・介護業務\n（入浴介助、食事介助などの一般介護業務のほか夜勤）\n\n・簡単なＰＣ入力あり",
        'required_qualifications' => '未経験OK',
        'salary' => '時給 1,400円～',
        'salary_detail' => null,
        'work_hours' => 'シフト制',
        'work_hours_detail' => "7時45分～17時30分\n\n※勤務日数や勤務時間は相談により対応可。",
        'holiday' => 'シフト制',
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "・雇用条件により、雇用保険、厚生年金等加入\n・通勤手当あり",
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => null,
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻郡利尻富士町鬼脇字鬼脇205-1',
        'work_address_detail' => "〒097-0211\n北海道利尻郡利尻富士町鬼脇字鬼脇205番地1\n\n鴛泊フェリーターミナルより車で30分\n利尻空港より車で35分",
        'pin_location' => 'oniwaki',
        'application_flow' => '応募フォーム',
    ],
    [
        'slug' => 'job-126',
        'title' => '介護員',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => '介護職',
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => "・介護業務\n（入浴介助、食事介助などの一般介護業務のほか夜勤）\n\n・簡単なＰＣ入力あり",
        'required_qualifications' => "・介護福祉士\n・実務者研修\n・初任者研修",
        'salary' => '月給 188,000円～',
        'salary_detail' => '期末勤勉手当（年4.6月）、寒冷地手当（11～3月）、住居手当、通勤手当、扶養手当、時間外勤務手当など',
        'work_hours' => 'シフト制',
        'work_hours_detail' => "勤務：07時45分～16時30分\nＣ勤：08時45分～17時30分\n夜勤：16時30分～09時00分",
        'holiday' => '完全週休2日制（土日祝休み）有給休暇、夏季休暇、結婚、忌引、出産等の特別休暇あり',
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "・市町村職員共済組合加入\n・退職手当組合加入",
        'housing_support_available' => 1,
        'housing_support_detail' => '住居手当',
        'smoking_policy' => null,
        'trial_period' => '6ケ月',
        'work_address' => '北海道利尻郡利尻富士町鬼脇字鬼脇205-1',
        'work_address_detail' => "利尻富士町デイサービスセンター\n〒097-0211\n北海道利尻郡利尻富士町鬼脇字鬼脇205番地1\n鴛泊フェリーターミナルより車で30分\n利尻空港より車で35分",
        'pin_location' => 'oniwaki',
        'application_flow' => '応募フォーム（姓名、性別、生年月日、電話番号、メールアドレス、住所入力）',
    ],
    [
        'slug' => 'job-130',
        'title' => '衛生業務作業員',
        'area' => 'oshidomari',
        'catch_copy' => null,
        'job_category' => null,
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => "〇し尿等収集運搬に関すること\n〇し尿等収集運搬収納に関すること\n〇遺体の火葬に関すること\n〇葬苑内の清掃に関すること\n〇葬苑周辺の清掃に関すること\n〇葬苑付属施設、設備の簡易な整備に関すること",
        'required_qualifications' => "学歴不問/未経験OK\n【必須】※し尿等収集運搬\n・大型自動車免許",
        'salary' => '月給 200,000円～',
        'salary_detail' => null,
        'work_hours' => '08：00～16：30',
        'work_hours_detail' => '〇08：00～16：30（割当により変動あり）',
        'holiday' => '週休日（毎週土、日曜日）',
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "〇労災保険\n〇厚生年金、地方公務員共済組合（加入要件を満たす場合）",
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => null,
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻富士町鴛泊字富士野6',
        'work_address_detail' => "〇利尻富士町役場\n〒097-0101\n北海道利尻郡利尻富士町鴛泊字富士野6番地\n\n〇利尻富士町葬苑\n〒097-0101\n北海道利尻郡利尻富士町鴛泊字栄町233番地2\n\n※し尿等収集運搬業務については利尻富士町内一円",
        'pin_location' => 'town_hall',
        'application_flow' => null,
    ],
    [
        'slug' => 'job-112',
        'title' => '介護支援専門員・社会福祉士',
        'area' => 'oshidomari',
        'catch_copy' => null,
        'job_category' => null,
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => "居宅介護支援事業所及び地域包括支援センターにおいて\nケアマネジメント業務、ケアプランの作成、相談支援等に従事します。\n\n※居宅介護支援事業所と地域包括支援センターの兼務となります。",
        'required_qualifications' => "・介護支援専門員及び社会福祉士の資格を有する方\n・普通自動車免許取得者、又は取得見込（予定）の方\n・地方公務員法第16条の欠格事項に該当しない方",
        'salary' => '月給 220,000円～',
        'salary_detail' => "利尻富士町職員の給与に関する条例及び規則に基づく給料及び扶養手当、住居手当、通勤手当、期末・勤勉手当、寒冷地手当等の諸手当を支給します。\n※採用前の経歴等に応じて、前歴換算した額を加算します。",
        'work_hours' => '固定時間制',
        'work_hours_detail' => "・8：30～17：15\n\n実働7時間45分\n休憩60分",
        'holiday' => '・完全週休2日制 ・有給休暇 ・育児休暇 ・産前産後休暇 ・慶弔休暇 ・夏季休暇',
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "・通勤手当\n・扶養手当\n・住居手当\n・期末・勤勉手当（6月・12月支給）\n・寒冷地手当（11月～3月）\n・赴任旅費あり\n・職員住宅あり\n・退職金制度あり",
        'housing_support_available' => 1,
        'housing_support_detail' => '職員住宅あり',
        'smoking_policy' => null,
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻郡利尻富士町鴛泊字栄町117',
        'work_address_detail' => "利尻富士町総合保健福祉センター\n〒097-0101\n北海道利尻郡利尻富士町鴛泊字栄町117\nバス停　鴛泊診療所前から徒歩2分",
        'pin_location' => 'health_center',
        'application_flow' => null,
    ],
    [
        'slug' => 'care-manager-shuhoen',
        'title' => '介護支援専門員',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => null,
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => '介護支援専門員としてのケアマネジメント業務',
        'required_qualifications' => '介護支援専門員の資格を有する方、地方公務員法第16条各号の欠格条項に該当しない方、普通自動車免許を所持又は所得見込みの方',
        'salary' => '月給 188,000円～',
        'salary_detail' => "高校卒188,000円～ 短大卒201,000円～ 大学卒220,000円～\n※初任給は、経歴に応じ加算される場合があります。\n※利尻富士町職員給与条例に基づき支給されます。",
        'work_hours' => '午前8：30～午後17：15',
        'work_hours_detail' => null,
        'holiday' => '土日祝日、年末年始（12/31～1/5）、年次有給休暇（年20日付与、初年度最大14日付与）、夏季休暇、結婚、忌引、出産等の休暇制度があります。',
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "市町村職員共済組合加入（健康保険、厚生年金）\n退職手当組合加入",
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => null,
        'trial_period' => '6ヶ月',
        'work_address' => '特別養護老人ホーム秀峰園',
        'work_address_detail' => "〒097-0211\n北海道利尻郡利尻富士町鬼脇字鬼脇205番地の1",
        'pin_location' => 'oniwaki',
        'application_flow' => '応募フォームへの入力（姓名、生年月日、電話番号、メールアドレス、住所など）',
    ],
    [
        'slug' => 'care-manager-rojinhoken',
        'title' => '介護支援専門員',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => null,
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => '介護支援専門員としてのケアマネジメント業務',
        'required_qualifications' => '介護支援専門員の資格を有する方、地方公務員法第16条各号の欠格条項に該当しない方、普通自動車免許を所持又は所得見込みの方',
        'salary' => '月給 188,000円～',
        'salary_detail' => "高校卒188,000円～ 短大卒201,000円～ 大学卒220,000円～\n※初任給は、経歴に応じ加算される場合があります。\n※利尻富士町職員給与条例に基づき支給されます。",
        'work_hours' => '午前8：30～午後17：15',
        'work_hours_detail' => null,
        'holiday' => "土日祝日、年末年始（12/31～1/5）\n年次有給休暇（年20日付与、初年度最大14日付与）、夏季休暇、結婚、忌引、出産等の休暇制度があります。",
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "市町村職員共済組合加入（健康保険、厚生年金）\n退職手当組合加入",
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => null,
        'trial_period' => '試用期間：6ヶ月',
        'work_address' => '利尻島老人保健施設',
        'work_address_detail' => "〒097-0211\n北海道利尻郡利尻富士町鬼脇字金崎332番地",
        'pin_location' => 'oniwaki',
        'application_flow' => null,
    ],
    [
        'slug' => 'care-manager-hokencenter',
        'title' => '介護支援専門員',
        'area' => 'oshidomari',
        'catch_copy' => null,
        'job_category' => null,
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => '介護支援専門員としてのケアマネジメント業務',
        'required_qualifications' => '介護支援専門員の資格を有する方、地方公務員法第16条各号の欠格条項に該当しない方、普通自動車免許を所持又は所得見込みの方',
        'salary' => '月給 188,000円～',
        'salary_detail' => "高校卒188,000円～ 短大卒201,000円～ 大学卒220,000円～\n※初任給は、経歴に応じ加算される場合があります。\n※利尻富士町職員給与条例に基づき支給されます。",
        'work_hours' => '午前8：30～午後17：15',
        'work_hours_detail' => null,
        'holiday' => "土日祝日、年末年始（12/31～1/5）\n年次有給休暇（年20日付与、初年度最大14日付与）、夏季休暇、結婚、忌引、出産等の休暇制度があります。",
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "市町村職員共済組合加入（健康保険、厚生年金）\n退職手当組合加入",
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => null,
        'trial_period' => '試用期間：6ヶ月',
        'work_address' => '総合保健福祉センター（居宅介護支援事業、地域包括支援センター）',
        'work_address_detail' => "〒097-0101\n北海道利尻郡利尻富士町鴛泊字栄町117番地",
        'pin_location' => 'health_center',
        'application_flow' => null,
    ],
    [
        'slug' => 'job-135',
        'title' => '送迎ドライバー',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => null,
        'recruitment_count' => null,
        'employment_type' => 'part_time',
        'description' => "○通リハ利用者送迎（運転業務）\n・通所リハビリ利用者の送迎\n・車両整備、点検、清掃、洗車等\n・その他",
        'required_qualifications' => '普通自動車第一種運転免許',
        'salary' => '時給 1,200円～',
        'salary_detail' => '通勤手当（費用弁償）',
        'work_hours' => '固定時間制（平日のみ、土日祝日除く）',
        'work_hours_detail' => "迎え 08：30 ～ 10：30 （実動2時間・休憩なし）\n送り 14：30 ～ 16：30 （実動2時間・休憩なし）\n\n1日～ 実動4時間",
        'holiday' => "完全週休2日制（土日祝日～休所）\n年次有給休暇（勤務日数等により決定）",
        'social_insurance' => '雇用保険 / 労災保険',
        'benefits' => "各種離島割引制度あり（フェリー、航空機）\nマイカー通勤可",
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => '敷地内禁煙',
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻郡利尻富士町鬼脇字金崎332',
        'work_address_detail' => "稚内より ハートランドフェリー 稚内～鴛泊（1時間40分）\n札幌より 航空機 丘珠～利尻（55分）\n宗谷バス 鴛泊ﾌｪﾘｰﾀｰﾐﾅﾙ～鬼脇秀峰園前（35分）降車徒歩3分",
        'pin_location' => 'oniwaki',
        'application_flow' => null,
    ],
    [
        'slug' => 'job-131',
        'title' => '保健師',
        'area' => 'oshidomari',
        'catch_copy' => null,
        'job_category' => null,
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => '乳児から高齢者まで、住民の生涯を通じた健康づくりを目指した保健事業全般',
        'required_qualifications' => "保健師資格取得者、又は令和8年3月までに取得予定の方\n普通自動車免許取得者、又は取得見込（予定）の方\n地方公務員法第16条の欠格事項に該当しない方",
        'salary' => '月給 254,300円～',
        'salary_detail' => '利尻富士町職員の給与に関する条例及び規則に基づく給料及び扶養手当、住居手当、通勤手当、期末・勤勉手当、寒冷地手当等の諸手当を支給します。 採用前の経歴等に応じて、前歴換算した額を加算します。',
        'work_hours' => '固定時間制',
        'work_hours_detail' => "8：30～17：15\n実働7時間45分\n休憩60分",
        'holiday' => "完全週休2日制\n有給休暇\n育児休暇\n産前産後休暇\n慶弔休暇\n夏季休暇",
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => '通勤手当、扶養手当、住居手当、期末・勤勉手当（6月・12月支給）、寒冷地手当（11月～3月）、赴任旅費、職員住宅、退職金制度',
        'housing_support_available' => 1,
        'housing_support_detail' => '職員住宅あり',
        'smoking_policy' => null,
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻郡利尻富士町鴛泊字栄町117',
        'work_address_detail' => "利尻富士町総合保健福祉センター\n〒097-0101\n北海道利尻郡利尻富士町鴛泊字栄町117\nバス停　鴛泊診療所前から徒歩2分",
        'pin_location' => 'health_center',
        'application_flow' => null,
    ],
    [
        'slug' => 'job-134',
        'title' => 'リハビリ介護職',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => '介護職',
        'recruitment_count' => null,
        'employment_type' => 'part_time',
        'description' => "○介護業務全般（リハ）\n・通所リハビリ利用者の援助、介助、送迎\n・入浴介助（入浴、着替え、身支度）\n・配膳、食事介助\n・移乗動作\n・見守り、レクリエーション\n・排せつ介助、オムツ交換\n・ケース記録、申送り、システム入力等\n・療法士施術補助、機能訓練等\n・その他",
        'required_qualifications' => "年齢：不問、学歴：不問、経験：不問、資格：不問\n（介護福祉士、介護職員実務者研修又は初任者研修修了者 歓迎）",
        'salary' => '時給 1,600円～',
        'salary_detail' => '通勤手当（費用弁償）',
        'work_hours' => '固定時間制（平日のみ、土日祝日除く）',
        'work_hours_detail' => "① 08：30 ～ 16：30 （実動7時間・休憩1時間） 送迎対応あり\n② 09：30 ～ 15：30 （実動5時間・休憩1時間）\n③ 09：30 ～ 12：30 （実動3時間・休憩なし）\n④ 12：30 ～ 15：30 （実動3時間・休憩なし）\n※希望勤務日数、希望時間帯等 要相談",
        'holiday' => '完全週休2日制（土日祝日～休所）、年次有給休暇（勤務日数等により決定）',
        'social_insurance' => '健康保険、厚生年金保険、雇用保険、労災保険',
        'benefits' => '北海道市町村職員共済組合加入、北海道市町村職員福祉協会加入、各種離島割引制度、マイカー通勤可',
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => '敷地内禁煙',
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻郡利尻富士町鬼脇字金崎332',
        'work_address_detail' => '稚内からハートランドフェリー、札幌から航空機でアクセス可能',
        'pin_location' => 'oniwaki',
        'application_flow' => '応募フォームへの入力（氏名、性別、生年月日、電話番号、メールアドレス、住所等）',
    ],
    [
        'slug' => 'job-133',
        'title' => 'リハビリ看護職',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => '医療・介護',
        'recruitment_count' => null,
        'employment_type' => 'part_time',
        'description' => "○看護業務全般（リハ）\n・通所リハビリ利用者の援助、介助、送迎\n・持参薬の服薬管理、介助\n・バイタル測定\n・痰吸引（必要者）\n・Ｄｒ回診補助、指示受け、コンサル等\n・ケース記録、申送り、システム入力等\n・排せつ介助、オムツ交換\n・入浴介助（着替え、身支度）\n・配膳、食事介助\n・移乗動作\n・見守り、レクリエーション\n・その他",
        'required_qualifications' => '看護師、准看護師（いずれか必須）',
        'salary' => '時給 1,600円～',
        'salary_detail' => '通勤手当（費用弁償）',
        'work_hours' => '固定時間制（平日のみ、土日祝日除く）',
        'work_hours_detail' => "① 8：30 ～ 16：30 （実動7時間・休憩1時間） 送迎対応あり\n② 9：30 ～ 15：30 （実動5時間・休憩1時間）\n③ 9：30 ～ 12：30 （実動3時間・休憩なし）\n④12：30 ～ 15：30 （実動3時間・休憩なし）\n※希望勤務日数、希望時間帯等 要相談",
        'holiday' => "完全週休2日制（土日祝日～休所）\n年次有給休暇（勤務日数等により決定）",
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "月額 88,000円以上の場合：北海道市町村職員共済組合加入、北海道市町村職員福祉協会加入、地方公務員災害補償基金加入\n各種離島割引制度あり（フェリー、航空機）\nマイカー通勤可",
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => '敷地内禁煙',
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻郡利尻富士町鬼脇字金崎332',
        'work_address_detail' => "稚内より ハートランドフェリー 稚内～鴛泊（1時間40分）\n札幌より 航空機 丘珠～利尻（55分）\n新千歳～利尻（50分）\nフェリー利用時：宗谷バス 鴛泊ﾌｪﾘｰﾀｰﾐﾅﾙ～鬼脇秀峰園前（35分）降車徒歩3分\n航空機利用時：宗谷バス 利尻空港～鬼脇秀峰園前（45分）降車徒歩3分",
        'pin_location' => 'oniwaki',
        'application_flow' => '応募フォームへ入力・送信',
    ],
    [
        'slug' => 'job-132',
        'title' => '介護職',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => '介護職',
        'recruitment_count' => null,
        'employment_type' => 'part_time',
        'description' => "○介護業務全般\n・利用者の生活援助、介護等\n・入浴介助\n・食事誘導、配膳、食事介助、おやつ提供\n・排せつ介助、オムツ交換\n・移乗動作\n・シーツ交換\n・レクリエーション\n・ケース記録、申送り、システム入力等\n・その他",
        'required_qualifications' => '年齢：不問、学歴：不問、経験：不問、資格：有資格者は介護業務全般（介護福祉士、介護職員実務者研修又は初任者研修修了者）無資格者は業務内容要相談',
        'salary' => '時給 1,200円～1,400円',
        'salary_detail' => '通勤手当（費用弁償）',
        'work_hours' => '交替制（シフト制）',
        'work_hours_detail' => "①A' 07：15 ～ 11：15 （実動4時間・休憩なし）\n②F 09：00 ～ 17：00 （実動7時間・休憩1時間）\n③A/ 12：15 ～ 16：15 （実動4時間・休憩なし）\n④G 12：00 ～ 18：00 （実動6時間・休憩なし）\n※希望勤務日数、希望時間帯等 要相談",
        'holiday' => 'シフトによる（希望勤務日数、希望時間帯等により要相談）年次有給休暇（勤務日数等により決定）',
        'social_insurance' => '健康保険、厚生年金保険、雇用保険、労災保険',
        'benefits' => '月額88,000円以上の場合：北海道市町村職員共済組合加入、北海道市町村職員福祉協会加入、地方公務員災害補償基金加入、各種離島割引制度あり',
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => '敷地内禁煙',
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻郡利尻富士町鬼脇字金崎332',
        'work_address_detail' => '稚内よりハートランドフェリー稚内～鴛泊（1時間40分）、札幌より航空機利用可、フェリー利用時は宗谷バス利用で35分、航空機利用時は45分',
        'pin_location' => 'oniwaki',
        'application_flow' => '応募フォームに入力・送信',
    ],
    [
        'slug' => 'job-111',
        'title' => '介護職（介護福祉士・介護職員実務者研修又は初任者研修修了者）',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => '介護職',
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => "○介護業務全般（日勤・夜勤）\n・看護職員と連携し、利用者の生活援助、介護等\n・入浴介助\n・食事誘導、配膳、食事介助、おやつ提供\n・排せつ介助、オムツ交換\n・移乗動作\n・シーツ交換\n・レクリエーション\n・ケース記録、申送り、システム入力等\n・歯科受診介助\n・その他",
        'required_qualifications' => '介護福祉士、介護職員実務者研修又は初任者研修修了者（いずれか必須）',
        'salary' => '月給 183,500円～188,000円',
        'salary_detail' => "介護福祉士：188,000円～\n介護職員実務者研修又は初任者研修修了者：183,500円～\n※基本給については、町給与条例等による学歴及び職歴換算等により決定\n【各種手当】 期末手当、勤勉手当、通勤手当、扶養手当、住宅手当、寒冷地手当（11～3月支給）、時間外勤務手当、夜間勤務手当、夜間看護等手当（1回3,300円）、介護士長手当（月10,000円）\n【昇給】 あり\n【賞与】 年2回（前年度実績 4.6ヶ月）",
        'work_hours' => '交替制（シフト制）',
        'work_hours_detail' => "日勤（早出）： 7：15 ～ 16：00 （休憩1時間）\n日勤（遅出）： 9：15 ～ 18：00 （休憩1時間）\n夜勤 　 ： 16：15 ～ 9：00 （休憩3時間） ※月4～5回程度",
        'holiday' => "シフトによる4週8休制（R7年度年間休日数：125日 年末年始及び夏季休暇含む）\n年末年始休暇（12/31～1/5）\n年次有給休暇（初年度：15日、2年目以降：20日）\n病気休暇\n特別休暇（結婚、忌引、出産、夏季休暇（6～10月の間で連続3日間）等）\n介護休暇\n育児休暇",
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => '北海道市町村職員共済組合加入、北海道市町村職員福祉協会加入、地方公務員災害補償基金加入、北海道市町村職員退職手当組合加入、赴任旅費あり、職員住宅あり、各種離島割引制度あり、医療技術者等職員就労奨励金制度あり、日勤時昼食夕食提供（自己負担）、町内保育所2箇所あり、マイカー通勤可',
        'housing_support_available' => 1,
        'housing_support_detail' => '職員住宅あり',
        'smoking_policy' => '敷地内禁煙',
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻郡利尻富士町鬼脇字金崎332',
        'work_address_detail' => "稚内より ハートランドフェリー 稚内～鴛泊（1時間40分）\n札幌より 航空機 丘珠～利尻（55分） 通年運航、4～10月の金土日2便体制\n新千歳～利尻（50分） 6～9月季節運航\nフェリー利用の場合：宗谷バス 鴛泊ﾌｪﾘｰﾀｰﾐﾅﾙ～鬼脇秀峰園前（35分）降車徒歩3分\n航空機利用の場合 ：宗谷バス 利尻空港～鬼脇秀峰園前（45分）降車徒歩3分",
        'pin_location' => 'oniwaki',
        'application_flow' => null,
    ],
    [
        'slug' => 'job-118',
        'title' => '看護職（看護師・准看護師）',
        'area' => 'oniwaki',
        'catch_copy' => null,
        'job_category' => '看護職',
        'recruitment_count' => null,
        'employment_type' => 'seishain',
        'description' => "○看護業務全般（日勤・夜勤）\n・医師の指示のもと、利用者の体調管理等\n・薬剤調整、作成（分包、一包化）、服薬介助\n・バイタル測定\n・Ｄｒ回診補助、指示受け、コンサル等\n・ケース記録、申送り、システム入力等\n・採血、点滴、酸素、経管栄養管理\n・排せつコントロール\n・受診介助、搬送、その他\n\n○その他介護業務\n・食事誘導、配膳、食事介助\n・排せつ介助、オムツ交換\n・移乗動作\n・シーツ交換\n・レクリエーション\n・その他",
        'required_qualifications' => "経験者のみ（医療機関又は福祉施設等8年以上の者）\n看護師、准看護師（いずれか必須）",
        'salary' => '月給 183,500円～201,000円',
        'salary_detail' => "看護師：201,000円～\n准看護士：183,500円～\n※基本給については、町給与条例等による学歴及び職歴換算等により決定\n【各種手当】 期末手当、勤勉手当、通勤手当、扶養手当、住宅手当、寒冷地手当（11～3月支給）、 時間外勤務手当、夜間勤務手当、夜間看護等手当（1回3,300円）、看護師長手当 （月10,000円）\n【昇給】 あり\n【賞与】 年2回（前年度実績 4.6ヶ月）\n【締日・支給】 月末締め、当月21日支給",
        'work_hours' => '交替制（シフト制）',
        'work_hours_detail' => "日勤： 8：15 ～ 17：00 （休憩1時間）\n夜勤： 16：15 ～ 9：00 （休憩3時間）\n※月6～7回程度",
        'holiday' => "シフトによる4週8休制（R7年度年間休日数：125日 年末年始及び夏季休暇含む）\n年末年始休暇（12/31～1/5）\n年次有給休暇（初年度：15日、2年目以降：20日）\n病気休暇\n特別休暇（結婚、忌引、出産、夏季休暇（6～10月の間で連続3日間）等）\n介護休暇\n育児休暇",
        'social_insurance' => '健康保険 / 厚生年金保険 / 雇用保険 / 労災保険',
        'benefits' => "北海道市町村職員共済組合加入（健康保険、厚生年金）\n北海道市町村職員福祉協会加入\n地方公務員災害補償基金加入\n北海道市町村職員退職手当組合加入\n赴任旅費あり（支給要件、上限あり）\n職員住宅あり\n各種離島割引制度あり（フェリー、航空機）\n医療技術者等職員就労奨励金制度あり\n50歳未満 1,000千円（勤務1年終了時300千円、2年終了時300千円、3年終了時400千円）\n50歳以上 500千円（勤務1年終了時150千円、2年終了時150千円、3年終了時200千円）\n日勤時、昼食、夕食提供（自己負担）\n町内保育所2箇所あり\nマイカー通勤可",
        'housing_support_available' => 1,
        'housing_support_detail' => '職員住宅あり',
        'smoking_policy' => '敷地内禁煙',
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻郡利尻富士町鬼脇字金崎332',
        'work_address_detail' => "稚内より ハートランドフェリー 稚内～鴛泊（1時間40分）\n札幌より 航空機 丘 珠～利尻（55分） 通年運航、4～10月の金土日2便体制\n新千歳～利尻（50分） 6～9月季節運航\n\nフェリー利用の場合：\n宗谷バス 鴛泊ﾌｪﾘｰﾀｰﾐﾅﾙ～鬼脇秀峰園前（35分）降車徒歩3分\n\n航空機利用の場合 ：\n宗谷バス 利尻空港～鬼脇秀峰園前（45分）降車徒歩3分",
        'pin_location' => 'oniwaki',
        'application_flow' => null,
    ],
    [
        'slug' => 'job-114',
        'title' => '航空機利用旅客の案内スタッフ',
        'area' => 'oshidomari',
        'catch_copy' => null,
        'job_category' => null,
        'recruitment_count' => null,
        'employment_type' => 'part_time',
        'description' => '旅客取扱業務（航空機利用旅客の誘導やご案内業務など）',
        'required_qualifications' => '高校卒業以上の者',
        'salary' => '月給 60,000円～100,000円',
        'salary_detail' => "・月額60,000円（5月、10月～3月）\n・月額100,000円（6月～9月）\n・通勤手当別途支給",
        'work_hours' => 'シフト制',
        'work_hours_detail' => "5月、10月～3月　 14：00～17：00\n6月～9月 　　　　13：00～17：00\n\n別途、教育時間、運航状況により勤務時間の延長等の変更あり\n増便業務の為、午前中の勤務あり",
        'holiday' => 'シフト制 有給休暇あり',
        'social_insurance' => null,
        'benefits' => '通勤手当支給',
        'housing_support_available' => 0,
        'housing_support_detail' => null,
        'smoking_policy' => null,
        'trial_period' => '試用期間：なし',
        'work_address' => '北海道利尻郡利尻富士町鴛泊字本泊1143',
        'work_address_detail' => "利尻空港（株式会社　利尻島振興公社）\n〒097-0101　北海道利尻郡利尻富士町鴛泊字本泊",
        'pin_location' => 'airport',
        'application_flow' => null,
    ],
];

/* ---------- Step 3: 19 件を新規挿入 ---------- */

$created = 0;
$errors = [];

foreach ($jobs as $job) {
    $post_id = wp_insert_post([
        'post_title'   => $job['title'],
        'post_name'    => $job['slug'],
        'post_status'  => 'publish',
        'post_type'    => 'job_posting',
        'post_content' => '',
    ], true);

    if (is_wp_error($post_id)) {
        $errors[] = $job['slug'] . ': ' . $post_id->get_error_message();
        continue;
    }
    $created++;

    // area タクソノミー（鴛泊 / 鬼脇）を割当
    if (!empty($job['area'])) {
        wp_set_object_terms($post_id, $job['area'], 'area', false);
    }

    // ACF required 項目のフォールバック
    $smoking = $job['smoking_policy'] ?? $default_smoking;
    $flow    = $job['application_flow'] ?? $default_flow;

    update_field('employment_type', $job['employment_type'], $post_id);
    update_field('job_category', $job['job_category'], $post_id);
    update_field('recruitment_count', $job['recruitment_count'], $post_id);
    update_field('catch_copy', $job['catch_copy'], $post_id);
    update_field('description', $job['description'], $post_id);
    update_field('required_qualifications', $job['required_qualifications'], $post_id);
    update_field('salary', $job['salary'], $post_id);
    update_field('salary_detail', $job['salary_detail'], $post_id);
    update_field('work_hours', $job['work_hours'], $post_id);
    update_field('work_hours_detail', $job['work_hours_detail'], $post_id);
    update_field('holiday', $job['holiday'], $post_id);
    update_field('social_insurance', $job['social_insurance'], $post_id);
    update_field('benefits', $job['benefits'], $post_id);
    update_field('housing_support_available', $job['housing_support_available'], $post_id);
    update_field('housing_support_detail', $job['housing_support_detail'], $post_id);
    update_field('smoking_policy', $smoking, $post_id);
    update_field('trial_period', $job['trial_period'], $post_id);
    update_field('work_address', $job['work_address'], $post_id);
    update_field('work_address_detail', $job['work_address_detail'], $post_id);
    update_field('pin_location', $job['pin_location'], $post_id);
    update_field('application_flow', $flow, $post_id);
}

/* ---------- Step 4: 完了レポート ---------- */

WP_CLI::success(sprintf(
    '求人インポート完了: 既存 %d 件を削除 / 新規 %d 件を作成',
    $deleted,
    $created
));

if (!empty($errors)) {
    WP_CLI::warning('エラー: ' . implode(' / ', $errors));
}
